In [2]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("../data/raw/football_matches_dataset.csv")

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

# First 5 rows
display(df.head())

# Data types
print("\nData Types:")
print(df.dtypes)

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Duplicate rows
print("\nDuplicate Rows:", df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

# Convert date
df["Match_Date"] = pd.to_datetime(
    df["Match_Date"],
    errors="coerce"
)

# Check invalid dates
print("Invalid Dates:", df["Match_Date"].isnull().sum())

# Numerical columns
numeric_columns = df.select_dtypes(
    include=np.number
).columns

print("\nNumerical Columns:")
print(numeric_columns.tolist())

# Check negative values
for col in numeric_columns:
    negative_count = (df[col] < 0).sum()
    if negative_count > 0:
        print(col, "negative values:", negative_count)

# Statistical summary
display(df.describe())



print("Cleaned dataset saved successfully!")

Dataset Shape: (3800, 18)

Columns:
['Match_ID', 'Match_Date', 'League', 'Home_Team', 'Away_Team', 'Venue_Type', 'Weather', 'Home_Goals', 'Away_Goals', 'Possession_Home_Percent', 'Shots_On_Target_Home', 'Shots_On_Target_Away', 'Fouls_Committed', 'Yellow_Cards', 'Red_Cards', 'Attendance', 'Possession_Away_Percent', 'Match_Result']

,Match_ID,Match_Date,League,Home_Team,Away_Team,Venue_Type,Weather,Home_Goals,Away_Goals,Possession_Home_Percent,Shots_On_Target_Home,Shots_On_Target_Away,Fouls_Committed,Yellow_Cards,Red_Cards,Attendance,Possession_Away_Percent,Match_Result
0,MTC-20869,2022-08-02,Championship League,Jaipur Lions,Goa Sharks,Home,Rainy,2,3,54,13,10,7,3,0,27877,46,Away Win
1,MTC-23099,2022-08-02,Cup Series,Delhi Dynamos,Chennai Titans,Neutral,Clear,2,1,67,5,12,16,2,0,20229,33,Home Win
2,MTC-22149,2022-08-03,Cup Series,Bengaluru FC,Delhi Dynamos,Home,Rainy,5,2,35,3,14,13,5,1,59436,65,Home Win
3,MTC-21109,2022-08-03,Premier Division,Delhi Dynamos,Kerala Blasters,Neutral,Windy,0,2,31,1,0,13,1,1,20339,69,Away Win
4,MTC-22321,2022-08-03,Premier Division,Kerala Blasters,Bengaluru FC,Neutral,Rainy,2,5,57,6,5,5,3,0,20143,43,Away Win

Data Types:
Match_ID                   object
Match_Date                 object
League                     object
Home_Team                  object
Away_Team                  object
Venue_Type                 object
Weather                    object
Home_Goals                  int64
Away_Goals                  int64
Possession_Home_Percent     int64
Shots_On_Target_Home        int64
Shots_On_Target_Away        int64
Fouls_Committed             int64
Yellow_Cards                int64
Red_Cards                   int64
Attendance                  int64
Possession_Away_Percent     int64
Match_Result               object
dtype: object

Missing Values:
Match_ID                   0
Match_Date                 0
League                     0
Home_Team                  0
Away_Team                  0
Venue_Type                 0
Weather                    0
Home_Goals                 0
Away_Goals                 0
Possession_Home_Percent    0
Shots_On_Target_Home       0
Shots_On_Target_Away       0
Fouls_Committed            0
Yellow_Cards               0
Red_Cards                  0
Attendance                 0
Possession_Away_Percent    0
Match_Result               0
dtype: int64

Duplicate Rows: 0
Invalid Dates: 0

Numerical Columns:
['Home_Goals', 'Away_Goals', 'Possession_Home_Percent', 'Shots_On_Target_Home', 'Shots_On_Target_Away', 'Fouls_Committed', 'Yellow_Cards', 'Red_Cards', 'Attendance', 'Possession_Away_Percent']

,Match_Date,Home_Goals,Away_Goals,Possession_Home_Percent,Shots_On_Target_Home,Shots_On_Target_Away,Fouls_Committed,Yellow_Cards,Red_Cards,Attendance,Possession_Away_Percent
count,3800,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000
mean,2023-10-11 23:37:15.789473792,2.553158,2.551579,49.889211,7.031316,6.924474,14.586053,3.021579,0.511579,34066.327368,50.110789
min,2022-08-02 00:00:00,0.000000,0.000000,30.000000,0.000000,0.000000,5.000000,0.000000,0.000000,2001.000000,30.000000
25%,2023-03-03 00:00:00,1.000000,1.000000,40.000000,3.000000,3.000000,10.000000,1.000000,0.000000,18267.500000,40.000000
50%,2023-10-07 12:00:00,3.000000,3.000000,50.000000,7.000000,7.000000,15.000000,3.000000,1.000000,34059.500000,50.000000
75%,2024-05-23 00:00:00,4.000000,4.000000,60.000000,11.000000,11.000000,20.000000,5.000000,1.000000,49873.250000,60.000000
max,2024-12-31 00:00:00,5.000000,5.000000,70.000000,14.000000,14.000000,24.000000,6.000000,1.000000,64974.000000,70.000000
std,NaN,1.699392,1.695564,11.810854,4.331586,4.375604,5.810689,1.989855,0.499932,18253.906705,11.810854

Cleaned dataset saved successfully!

In [ ]:

# Total Goals
df["Total_Goals"] = (
    df["Home_Goals"] +
    df["Away_Goals"]
)

# Goal Difference
df["Goal_Difference"] = (
    df["Home_Goals"] -
    df["Away_Goals"]
)

# Absolute Goal Difference
df["Absolute_Goal_Difference"] = (
    df["Goal_Difference"].abs()
)

# Total Shots on Target
df["Total_Shots_On_Target"] = (
    df["Shots_On_Target_Home"] +
    df["Shots_On_Target_Away"]
)

df["Possession_Difference"] = (
    df["Possession_Home_Percent"] -
    df["Possession_Away_Percent"]
)


df["Absolute_Possession_Difference"] = (
    df["Possession_Difference"].abs()
)


df["Year"] = df["Match_Date"].dt.year


df["Month"] = df["Match_Date"].dt.month


df["Day_Name"] = df["Match_Date"].dt.day_name()

# Display first 5 rows
display(df.head())

df.to_csv(
    "../data/processed/football_cleaned.csv",
    index=False
)
print("Cleaned dataset saved successfully!")

,Match_ID,Match_Date,League,Home_Team,Away_Team,Venue_Type,Weather,Home_Goals,Away_Goals,Possession_Home_Percent,...,Match_Result,Total_Goals,Goal_Difference,Absolute_Goal_Difference,Total_Shots_On_Target,Possession_Difference,Absolute_Possession_Difference,Year,Month,Day_Name
0,MTC-20869,2022-08-02,Championship League,Jaipur Lions,Goa Sharks,Home,Rainy,2,3,54,...,Away Win,5,-1,1,23,8,8,2022,8,Tuesday
1,MTC-23099,2022-08-02,Cup Series,Delhi Dynamos,Chennai Titans,Neutral,Clear,2,1,67,...,Home Win,3,1,1,17,34,34,2022,8,Tuesday
2,MTC-22149,2022-08-03,Cup Series,Bengaluru FC,Delhi Dynamos,Home,Rainy,5,2,35,...,Home Win,7,3,3,17,-30,30,2022,8,Wednesday
3,MTC-21109,2022-08-03,Premier Division,Delhi Dynamos,Kerala Blasters,Neutral,Windy,0,2,31,...,Away Win,2,-2,2,1,-38,38,2022,8,Wednesday
4,MTC-22321,2022-08-03,Premier Division,Kerala Blasters,Bengaluru FC,Neutral,Rainy,2,5,57,...,Away Win,7,-3,3,11,14,14,2022,8,Wednesday

Cleaned dataset saved successfully!